name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: 11
          server-id: github
          distribution: 'temurin'
          cache: 'maven'

      # need to be after actions/setup-java@v4
      # and repeat github server id since setting.xml is replaced
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: >
            [
              {
                "id": "bar",
                "name": "Bonita Artifact Repository",
                "url": "https://bonitasoft.jfrog.io/artifactory/releases",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          plugin_repositories: >
            [
              {
                "id": "bar",
                "name": "Bonita Artifact Repository",
                "url": "https://bonitasoft.jfrog.io/artifactory/releases",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          servers: >
            [
              {
                "id": "bar",
                "username": "${{ secrets.JFROG_USER }}",
                "password": "${{ secrets.JFROG_TOKEN }}"
              }
            ]


      - name: Build connector
        run: ./mvnw clean verify

      - name: Get version
        id: get-version
        run: |
          VERSION=$( ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout )
          FINAL_NAME=$( ./mvnw help:evaluate -Dexpression=project.build.finalName -q -DforceStdout )
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=final-name::$FINAL_NAME"
      - name: Display version
        id: display-version
        run: |
          echo "version: ${{ steps.get-version.outputs.version }}"
          echo "final_name: ${{ steps.get-version.outputs.final-name }}"

      - name: Publish to Github Package
        run: ./mvnw --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
